import Providers from "./components/Providers";
import Navbar from "./components/Navbar";
import "./globals.css";
import Toaster from "./components/Toaster";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Toaster />
          {/* @ts-expect-error Server Component */}
          <Navbar></Navbar>
          {children}
        </Providers>
      </body>
    </html>
  );
}
